#!/bin/bash
#
# notify_telegram_service
# Nagios notification plugin to fire Telegram (bot) service notifications
#
# Version: 2018-10-16H10:17:21
#
# Copyright (C) 2017 Davide Pucci <d.pucci@i-node.it> for I-Node S.r.l.
#
# This program is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see http://www.gnu.org/licenses/.

# auxiliary functions

function help()		{ echo -e "Usage:\n\t$(basename $0) -t <bot_token> -c <chat_id>"; exit 0; }

# shell setup

# arguments parsing

while [[ $# -gt 0 ]]; do
	case "$1" in
		-h|--help)
			help
			;;
		-t|--token)
			TELEGRAM_BOT_TOKEN="$2"
			shift
			;;
		-c|--chat-id)
			TELEGRAM_CHAT_ID="$2"
			shift
			;;

		--host-address)
			TELEGRAM_HOST_ADDRESS="$2"
			shift
			;;
		--host-alias)
			TELEGRAM_HOST_ALIAS="$2"
			shift
			;;
		--host-display-name)
			TELEGRAM_HOST_DISPLAY_NAME="$2"
			shift
			;;
		--long-date-time)
			TELEGRAM_LONG_DATE_TIME="$2"
			shift
			;;
		--notification-author-name)
			TELEGRAM_NOTIFICATION_AUTHOR_NAME="$2"
			shift
			;;
		--notification-comment)
			TELEGRAM_NOTIFICATION_COMMENT="$2"
			shift
			;;
		--notification-type)
			TELEGRAM_NOTIFICATION_TYPE="$2"
			shift
			;;
		--service-desc)
			TELEGRAM_SERVICE_DESC="$2"
			shift
			;;
		--service-display-name)
			TELEGRAM_SERVICE_DISPLAY_NAME="$2"
			shift
			;;
		--service-output)
			TELEGRAM_SERVICE_OUTPUT="$2"
			shift
			;;
		--service-state)
			TELEGRAM_SERVICE_STATE="$2"
			shift
			;;
	esac
	shift
done

# arguments validation

if [ -z "${TELEGRAM_BOT_TOKEN}" ] || [ -z "${TELEGRAM_CHAT_ID}" ]; then
	help
fi

# effective script

TEMPLATE=$(cat <<EOF
*$TELEGRAM_HOST_DISPLAY_NAME*: \`$TELEGRAM_SERVICE_DISPLAY_NAME\` is $TELEGRAM_SERVICE_STATE

Notification Type: $TELEGRAM_NOTIFICATION_TYPE

Service: \`$TELEGRAM_SERVICE_DESC\`
Host: $TELEGRAM_HOST_ALIAS
Address: $TELEGRAM_HOST_ADDRESS
State: $TELEGRAM_SERVICE_STATE

Date/Time: $TELEGRAM_LONG_DATE_TIME

Additional Info:
\`\`\`
$TELEGRAM_SERVICE_OUTPUT
\`\`\`
EOF
)

if [ ! -z "${TELEGRAM_NOTIFICATION_AUTHOR_NAME}" ] && [ ! -z "${TELEGRAM_NOTIFICATION_COMMENT}" ]; then
	TEMPLATE=$(cat <<EOF
$TEMPLATE

Comment:
*$TELEGRAM_NOTIFICATION_AUTHOR_NAME*
\`\`\`
$TELEGRAM_NOTIFICATION_COMMENT
\`\`\`
EOF
	)
fi

curl --silent --output /dev/null \
	--data-urlencode "chat_id=${TELEGRAM_CHAT_ID}" \
	--data-urlencode "text=${TEMPLATE}" \
	--data-urlencode "parse_mode=Markdown" \
	"https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage"
